### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by willtebbutt**

### CODE REVIEW

**Comment by willtebbutt** [comment]
This actually might require renaming the internal parameter of `ScaledKernel` to avoid weird naming inconsistencies, but this is definitely the right idea. The parameter of the scaled kernel is its variance, as opposed to std. dev.

**Comment by willtebbutt** [comment]
> That sounds like a reasonable change. I will then do all the renaming of ScaledKernel

@theogf no need, I've just done it!

**Comment by theogf** [comment]
Just saw that. Maybe that would be good to also add a `variance` function that returns sigma for a ScaledKernel and 1 for other kernels? It just might end up complicated for nested kernels...

**Comment by willtebbutt** [comment]
> Just saw that. Maybe that would be good to also add a variance function that returns sigma for a ScaledKernel and 1 for other kernels? It just might end up complicated for nested kernels...

This sounds reasonable. Could we do it in a different PR though please?

**Pull request merged**
